# Generated by Django 4.1.2 on 2022-10-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pot',
            new_name='Post',
        ),
    ]
